### ISSUE TITLE
PeerTube JavaScript included on every page

### ISSUE THREAD

**Issue by reclaimingmytime** [JupiterBroadcasting/jupiterbroadcasting.com#328]
When I look at the browser console on any page other than the live page (e.g. https://new.jupiterbroadcasting.com/sponsors/), I get the following error:

```
(index):102 Uncaught (in promise) TypeError: Cannot set properties of null (setting 'src')
    at (index):102:73
```

It seems to be that the code embedded in the _jb-tube.html_ partial is included on every page, not just the live page.

https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/blob/3216265083a3ea39b98950cc1443e49c4a981962/themes/jb/layouts/partials/live/jb-tube.html#L1

**Comment by gerbrent** [comment]
nice investigative work!

**Comment by gerbrent** [comment]
@elreydetoda : closed because solved by #425?

**Comment by elreydetoda** [comment]
Yes, @ChanceM 's #425 solved this by doing a query on each page to see if the liveStream id is present. Explained here: https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/425#pullrequestreview-1121249814

**Comment by elreydetoda** [comment]
Thinking about this again for a second, technically the #425 didn't "solve" every page loading the JS. It's just preventing the error from happening by checking if the expected embed element exists and only setting the `.src` attrib (which was causing the error) if it does.

So, I'd say it _technically_ patched the issue not solved 😅

**Comment by ozcoder** [comment]
I think a better way is to detect the page it is going to be included in, and not including it in pages it shouldn't be on.

**Comment by elreydetoda** [comment]
I'll actually re-open this since it's not fully remediated then. Just so we don't lose track of doing a "proper" fix for it.

**Comment by ChanceM** [comment]
> I'll actually re-open this since it's not fully remediated then. Just so we don't lose track of doing a "proper" fix for it.

I mean technically we could remove a few lines and copy the rest to another file but, then we would need to maintain the same code in two places, as the same query for the live show embed is used to mark the live menu item. I think this is a sane half measure to eliminate the error and either not maintain the code twice or add another file request to the pages.
